"""Deterministic signal weights, labels, and colors."""

from app.models import Signal

CATEGORY_COLORS: dict[str, str] = {
    "sender": "#A67C52",
    "links": "#0B3D91",
    "attachments": "#E91E63",
    "content": "#000000",
    "headers": "#6A1B9A",
    "metadata": "#4A4A4A",
}

CATEGORY_LABELS: dict[str, str] = {
    "sender": "Sender Identity",
    "links": "Links and URLs",
    "attachments": "Attachments",
    "content": "Content and Social Engineering",
    "headers": "Headers and Authentication",
    "metadata": "Metadata and Context",
}

SIGNAL_DEFINITIONS: dict[str, dict[str, object]] = {
    "sender.reply_to_mismatch": {
        "category": "sender",
        "name": "Reply-To mismatch",
        "severity": "high",
        "points": 15,
        "explanation": "The Reply-To domain differs from the sender domain, which may indicate reply redirection or impersonation.",
    },
    "sender.brand_impersonation": {
        "category": "sender",
        "name": "Display name imitates a known brand",
        "severity": "high",
        "points": 15,
        "explanation": "The sender display name references a known brand, but the sender domain does not appear to belong to that brand. This may indicate impersonation.",
    },
    "sender.free_provider_org": {
        "category": "sender",
        "name": "Free email provider pretending to be an organization",
        "severity": "medium",
        "points": 12,
        "explanation": "The sender uses a free email provider while presenting as an organization or business function, which may indicate impersonation.",
    },
    "sender.typosquat_domain": {
        "category": "sender",
        "name": "Sender domain appears typo-squatted",
        "severity": "high",
        "points": 15,
        "explanation": "The sender domain resembles a known brand with small character changes, which may indicate impersonation.",
    },
    "sender.body_domain_mismatch": {
        "category": "sender",
        "name": "Sender domain mentioned in body does not match From domain",
        "severity": "medium",
        "points": 10,
        "explanation": "A domain mentioned in the message body differs from the sender domain, which may indicate a misleading sender identity.",
    },
    "sender.suspicious_formatting": {
        "category": "sender",
        "name": "Suspicious sender formatting",
        "severity": "low",
        "points": 6,
        "explanation": "The sender field has unusual formatting that makes the true sender identity harder to understand.",
    },
    "links.http_link": {
        "category": "links",
        "name": "HTTP link",
        "severity": "low",
        "points": 8,
        "explanation": "The message contains a non-HTTPS link, which can expose users to tampering or unsafe redirects.",
    },
    "links.ip_url": {
        "category": "links",
        "name": "IP-based URL",
        "severity": "high",
        "points": 15,
        "explanation": "The message links directly to an IP address instead of a readable domain, which is often used to hide destination identity.",
    },
    "links.shortened_url": {
        "category": "links",
        "name": "Shortened URL",
        "severity": "medium",
        "points": 10,
        "explanation": "The message uses a URL shortener, which hides the final destination from the user.",
    },
    "links.punycode_domain": {
        "category": "links",
        "name": "Punycode domain",
        "severity": "high",
        "points": 15,
        "explanation": "The message contains a punycode domain, which can be used to disguise lookalike domains.",
    },
    "links.suspicious_tld": {
        "category": "links",
        "name": "Suspicious TLD",
        "severity": "low",
        "points": 8,
        "explanation": "The message links to a domain with a top-level domain commonly seen in risky campaigns.",
    },
    "links.more_than_5": {
        "category": "links",
        "name": "More than 5 links",
        "severity": "low",
        "points": 7,
        "explanation": "The message contains more than five links, increasing the chance of confusing or misleading destinations.",
    },
    "links.anchor_mismatch": {
        "category": "links",
        "name": "Anchor text domain differs from actual URL domain",
        "severity": "high",
        "points": 15,
        "explanation": "A link displays one domain but points to another, which may indicate a deceptive link.",
    },
    "links.keyword_near_url": {
        "category": "links",
        "name": "Login/payment/security keyword near link",
        "severity": "medium",
        "points": 10,
        "explanation": "A link appears near login, payment, or security language, which may indicate credential or financial targeting.",
    },
    "attachments.executable_extension": {
        "category": "attachments",
        "name": "Executable-like extension",
        "severity": "critical",
        "points": 20,
        "explanation": "An attachment filename has an executable-like extension. MailWatch Tower does not open attachments.",
    },
    "attachments.macro_office": {
        "category": "attachments",
        "name": "Macro-enabled Office file",
        "severity": "high",
        "points": 18,
        "explanation": "An attachment appears to be a macro-enabled Office document, which can carry risky automation.",
    },
    "attachments.archive": {
        "category": "attachments",
        "name": "Archive file",
        "severity": "medium",
        "points": 10,
        "explanation": "An attachment appears to be an archive file, which can hide file types from casual inspection.",
    },
    "attachments.double_extension": {
        "category": "attachments",
        "name": "Double extension",
        "severity": "critical",
        "points": 20,
        "explanation": "An attachment filename uses multiple extensions, which can be used to disguise the true file type.",
    },
    "attachments.misleading_filename": {
        "category": "attachments",
        "name": "Misleading filename",
        "severity": "medium",
        "points": 12,
        "explanation": "An attachment name combines financial lure wording with a file type that deserves caution.",
    },
    "attachments.urgent_payment_language": {
        "category": "attachments",
        "name": "Attachment plus urgent/payment language",
        "severity": "medium",
        "points": 10,
        "explanation": "The message combines an attachment with urgent or payment language, a common social engineering pattern.",
    },
    "content.urgency": {
        "category": "content",
        "name": "Urgency language",
        "severity": "medium",
        "points": 10,
        "explanation": "The message uses urgency language to pressure the user into acting quickly.",
    },
    "content.threat": {
        "category": "content",
        "name": "Threat language",
        "severity": "medium",
        "points": 10,
        "explanation": "The message uses threatening language that may pressure the user into unsafe action.",
    },
    "content.credential_request": {
        "category": "content",
        "name": "Credential request",
        "severity": "high",
        "points": 15,
        "explanation": "The message asks the user to provide, verify, or reset credentials.",
    },
    "content.payment_request": {
        "category": "content",
        "name": "Payment or wire transfer request",
        "severity": "high",
        "points": 12,
        "explanation": "The message requests payment, banking, or wire transfer activity.",
    },
    "content.mfa_security_reset": {
        "category": "content",
        "name": "MFA/security reset lure",
        "severity": "medium",
        "points": 12,
        "explanation": "The message references MFA, password reset, or security reset language that may be used as a lure.",
    },
    "content.invoice_order_payment": {
        "category": "content",
        "name": "Fake invoice/order/payment lure",
        "severity": "medium",
        "points": 10,
        "explanation": "The message uses invoice, order, or payment wording commonly used in phishing lures.",
    },
    "content.delivery_package": {
        "category": "content",
        "name": "Delivery/package lure",
        "severity": "low",
        "points": 8,
        "explanation": "The message references delivery or package tracking language that may be used as a lure.",
    },
    "content.hr_payroll": {
        "category": "content",
        "name": "HR/payroll lure",
        "severity": "medium",
        "points": 10,
        "explanation": "The message references HR or payroll themes commonly used in social engineering.",
    },
    "content.generic_greeting": {
        "category": "content",
        "name": "Generic greeting",
        "severity": "low",
        "points": 5,
        "explanation": "The message uses a generic greeting instead of addressing the recipient specifically.",
    },
    "content.bypass_process": {
        "category": "content",
        "name": "Request to bypass normal process",
        "severity": "high",
        "points": 12,
        "explanation": "The message asks the user to bypass normal procedures, which is a common social engineering tactic.",
    },
    "headers.dmarc_fail": {
        "category": "headers",
        "name": "DMARC fail",
        "severity": "high",
        "points": 15,
        "explanation": "Authentication results indicate DMARC failed, which may indicate sender spoofing.",
    },
    "headers.spf_fail": {
        "category": "headers",
        "name": "SPF fail",
        "severity": "medium",
        "points": 10,
        "explanation": "Authentication results indicate SPF failed, which may indicate unauthorized sending infrastructure.",
    },
    "headers.dkim_fail": {
        "category": "headers",
        "name": "DKIM fail",
        "severity": "medium",
        "points": 10,
        "explanation": "Authentication results indicate DKIM failed, which may indicate message authentication problems.",
    },
    "headers.missing_auth_results": {
        "category": "headers",
        "name": "Missing Authentication-Results header",
        "severity": "low",
        "points": 5,
        "explanation": "The message does not include an Authentication-Results header for the backend to inspect.",
    },
    "headers.return_path_mismatch": {
        "category": "headers",
        "name": "From domain and Return-Path domain mismatch",
        "severity": "medium",
        "points": 10,
        "explanation": "The Return-Path domain differs from the visible From domain, which may indicate sender inconsistency.",
    },
}


def make_signal(signal_id: str) -> Signal:
    """Build a Signal model from a known signal id."""
    definition = SIGNAL_DEFINITIONS[signal_id]
    category = str(definition["category"])
    return Signal(
        category=category,
        category_label=CATEGORY_LABELS[category],
        category_color=CATEGORY_COLORS[category],
        name=str(definition["name"]),
        severity=str(definition["severity"]),
        points=int(definition["points"]),
        explanation=str(definition["explanation"]),
    )
